version: "3"
services:
  api:
    build: .
    command: cargo-watch -x run
    volumes:
      - ./api:/var/app
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ENV=dev
  db:
    image: mysql:latest
    environment:
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    
  
  