version: "3.1"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpw
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_DATABASE=heroes
  api:
    build: .
    command: cargo-watch -x run
    volumes:
      - ./api:/var/app
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ENV=dev
      - DATABASE_URL=mysql://demo:demo@db/heroes
    depends_on:
      - db
    
  
  