[development]
address = "0.0.0.0"
port = 8000
# workers = [number of cpus * 2]
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

# [global.databases]
# diesel_mysql_pool = { url = "mysql://demo:demo@db/heroes" }